type Transfers {
  id: ID!
  collection: String!
  token_id: BigInt!
  chain_id: Int!
  recipient: String!
  quantity: BigInt!
  # InProcess only - null for Catalog/Sound.xyz
  value: BigInt
  currency: String
  transaction_hash: String!
  block_number: BigInt!
  transferred_at: Int!
}

type ZoraMedia_Moments {
  id: ID!
  collection: String!
  token_id: BigInt!
  owner: String!
  uri: String
  metadata_uri: String
  chain_id: Int!
  created_at: Int!
  updated_at: Int!
  transaction_hash: String!
}

type ZoraMedia_Admins {
  id: ID!
  admin: String!
  collection: String!
  token_id: BigInt!
  chain_id: Int!
  permission: Int!
  updated_at: Int!
}
